#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = chocolate-launcher
APP_NAME = chocolate-launcher
chocolate-launcher_APPLICATION_ICON = 48x48.png


#
# Resource files
#
chocolate-launcher_RESOURCE_FILES = \
Resources/launcher.gorm \
Resources/Main.gsmarkup \
Resources/MainMenu-GNUstep.gsmarkup \
Resources/MainMenu-OSX.gsmarkup \
Resources/48x48.png 


#
# Header files
#
chocolate-launcher_HEADER_FILES = \
AppController.h \
Execute.h \
IWADController.h \
IWADLocation.h \
LauncherManager.h

#
# Class files
#
chocolate-launcher_OBJC_FILES = \
AppController.m \
Execute.m \
IWADController.m \
IWADLocation.m \
LauncherManager.m

#
# Other sources
#
chocolate-launcher_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
